"""Add username and other missing columns to user table

Revision ID: 0f8b63a18749
Revises: 15919a743bb3
Create Date: 2025-12-26 23:29:48.429843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8b63a18749'
down_revision: Union[str, Sequence[str], None] = '15919a743bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False, server_default='temporary_user'))
    # Fill existing users with their email as username
    op.execute("UPDATE users SET username = email")
    # Remove the server_default after update
    op.alter_column('users', 'username', server_default=None)
    
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    
    # First make university nullable to allow cleanup
    op.alter_column('users', 'university', existing_type=sa.VARCHAR(), nullable=True)
    
    # Data cleanup for university column
    op.execute("UPDATE users SET university = 'ESTIN' WHERE university = 'estin'")
    op.execute("UPDATE users SET university = NULL WHERE university = ''")

    # Handle Enum creation if it doesn't exist
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'universityenum') THEN CREATE TYPE universityenum AS ENUM ('ESTIN', 'ESI', 'EPAU', 'USTHB'); END IF; END $$;")

    op.alter_column('users', 'university',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ESTIN', 'ESI', 'EPAU', 'USTHB', name='universityenum'),
               postgresql_using='CASE WHEN university IN (\'ESTIN\', \'ESI\', \'EPAU\', \'USTHB\') THEN university::universityenum ELSE NULL END',
               nullable=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.alter_column('users', 'university',
               existing_type=sa.Enum('ESTIN', 'ESI', 'EPAU', 'USTHB', name='universityenum'),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
