"""create users table

Revision ID: 22bb610c28ca
Revises: fd1683f98d45
Create Date: 2025-12-15 13:43:02.867248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22bb610c28ca'
down_revision: Union[str, Sequence[str], None] = 'fd1683f98d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'university',
               existing_type=postgresql.ENUM('ESTIN', 'ESI', 'EPAU', 'USTHB', name='universityenum'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('users', 'university',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ESTIN', 'ESI', 'EPAU', 'USTHB', name='universityenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
